### ISSUE TITLE
Client not found

### ISSUE THREAD

**Issue by ghost** [SupremeMortal/SynapseTransfer#3]
Hello.

You can add config.yml with list of servers?

Thx @SupremeMortal

**Comment by SupremeMortal** [comment]
The names of the servers are set in the descriptions of the SynapseAPI plugin configs. It would be more efficient to change them there

**Comment by ghost** [comment]
Wat... How? @SupremeMortal

**Comment by ghost** [comment]
@SupremeMortal I don't understand .You can explain me?

**Comment by SupremeMortal** [comment]
In your `/plugins/SynapseAPI/config.yml` Set the `description` to what you want the server to be called per Nukkit server

**Comment by SupremeMortal** [comment]
I updated the Readme aswell. https://github.com/SupremeMortal/SynapseTransfer/blob/master/README.md

**Comment by ghost** [comment]
@SupremeMortal i'm using /server and get error and say: Clients not found.

**Comment by SupremeMortal** [comment]
You got any Screenshots or error codes?

**Comment by SupremeMortal** [comment]
@NycuRO Make sure you have the most update to date version of the plugin from here.
https://ci.potestas.xyz/job/SynapseTransfer/
